### ISSUE TITLE
Experiment with using Roact 17

### ISSUE THREAD

**Issue by vocksel** [vocksel/flipbook#152]
Roact 17 is a port of React 17 to Luau can be be found as part of [grilme99/CorePackages](https://github.com/grilme99/CorePackages). Would be cool to experiment with consuming it in flipbook as an experiment. If we like including it, flipbook would then become a great learning resource for the use of Roact 17

**Comment by passhley** [comment]
I've been using the new React & ReactRoblox packages, could definitely implement those.
