### ISSUE TITLE
Support roblox-ts

### ISSUE THREAD

**Issue by sasial-dev** [vocksel/flipbook#164]
Currently the plugins errors:
![image](https://user-images.githubusercontent.com/44125644/211422645-e48d92b2-5cfd-49bf-823f-236cafb49ec1.png)

**Comment by vocksel** [comment]
I'm unfamiliar with roblox-ts. Is it somehow attempting to transpile the plugin? Is it not possible to use the plugin as-is while using roblox-ts for your codebase? Would love some more details on how you're trying to use flipbook here

**Comment by sasial-dev** [comment]
Ideally I'd use your plugin as-is w. roblox-ts; I shouldn't need to mess with your plugin source at all etc. By the looks of the error, it looks like it's an issue with the upstream dependency `roact-spring`. It's trying to find my bundled roact through roblox-ts instead of using the plugin's bundled version of roact...

**Comment by sasial-dev** [comment]
cc @chriscerie, would love to see if you can check if this is an upstream issue or not!

**Comment by vocksel** [comment]
Ahh I see, it internally looks for roblox-ts. If a fix for this gets published I'll be sure to update to the latest version

**Comment by vocksel** [comment]
@sasial-dev Just upgraded to RoactSpring 1.1.3. You can download the latest build from the bottom of this page: https://github.com/vocksel/flipbook/actions/runs/3981367612

Let me know if this solves your issue
