### ISSUE TITLE
Wrap all stories with context provider?

### ISSUE THREAD

**Issue by notme1560** [vocksel/flipbook#167]
I am using RoactRodux to wrap my whole tree with a provider of the Rodux store. My components are also wrapped in `RoactRodux.connect` and won't render in flipbook unless there is a provider somewhere above them in the tree. I can get around this by wrapping each story with the provider:
```lua
return {
	summary = "test",
	story = Roact.createElement(RoactRodux.StoreProvider, {
		store = store,
	}, {
		Main = Roact.createElement(Component)
	})
}
```
But would it be possible to instead do this globally?

**Comment by vocksel** [comment]
Yeah, this is something we want to do as part of #95 by introducing middleware support
