### ISSUE TITLE
AutomaticSize on canvas provides weird issues with components that change size.

### ISSUE THREAD

**Issue by passhley** [vocksel/flipbook#173]
Due to us using AutomaticSize on the preview area, if a user tries to preview a component that updates in size, or something of the sort, it will bug out. Need to find a better solution to the canvas area.

**Comment by nomer888** [comment]
I'm trying to preview a component with size (1, 0, 1, 0) and it's not taking up the area of the canvas - it sounds like this issue might be the reason why?

**Comment by vocksel** [comment]
I'm looking into this and figuring out cases to account for. Currently I'm considering:
1. Components that resize themselves
2. Offset-based components (i.e. an offset bigger than the preview)
3. Scale-based components (i.e. `UDim2.fromScale(1, 1)`)
4. AutomaticSize-based components (both `AutomaticSize.Y` and `AutomaticSize.XY`
5. ScrollingFrame-based components
Anything else to look out for?
