### ISSUE TITLE
Supply one copy of Roact in the storybook, rather than in each story

### ISSUE THREAD

**Issue by vocksel** [vocksel/flipbook#46]
Currently, the story's version of Roact has to be passed in for each individual story. Instead, the storybook should have a `roact` property that will be used if the story is missing its own `roact` property.

**Comment by passhley** [comment]
Could do something in a settings panel where you can press the input area and then select roact and itll set your env Roact module. Could save it somewhere low key as an ObjectValue.

**Comment by vocksel** [comment]
A settings panel might be out of scope. Generally all configuration is done via `.storybook` and `.story` files, and I am unsure how well introducing plugin-generated instances will work with a Rojo workflow
