### ISSUE TITLE
Allow multiple stories to be included in the same story file

### ISSUE THREAD

**Issue by vocksel** [vocksel/flipbook#48]
```lua
return {
    summary = "Storybook with many stories",
    roact = Roact,
    stories = {
        {
            name = "First story",
            summary = "Its own summary",
            story = Roact.createElement(...)
        },

        {
            name = "Second story",
            story = Roact.createElement(...)
        }
    }
}
```

**Comment by passhley** [comment]
I feel like this is somewhat of a bad idea? My issue would just be the amount of clutter it would provide. Especially 2 stories with 2 controls. Also some people might end up having completely different components in the same story file which just doesn't seem like a good organizational move. I believe keeping it as 1 story per file is a good idea so people separate out their components.

**Comment by vocksel** [comment]
I understand your concerns here. The idea behind this is:
- The `stories` array takes a subset of a `Story` which only includes `name`, `summary`, and `story`.
- Then a story [like this](https://github.com/vocksel/roact-storybook/blob/3d01992573ffaa8139407c552611b65df68f3069/src/Components/Button.story.lua) can be split up into 3 sub-stories to supply a summary and isolated environment for each button.

This is something the Developer Storybook does, though I'm unsure how much it is used in practice! Maybe it is in fact an anti-pattern and we should just stick with the singular `story` field. We can leave this in the backlog for now and if there's demand for it then it can be implemented

**Comment by passhley** [comment]
I do like the idea of sub stories, that's what my idea was behind "Component Groups" was. I'd definitely like to look into ideas around it.
