### ISSUE TITLE
Fix functional types

### ISSUE THREAD

**Issue by passhley** [vocksel/flipbook#55]
Correct me if I'm wrong, but if a function doesn't explicitly return ``nil``, it returns nothing, which are different things? I see a lot of functional types written as ``() -> nil`` but I believe it's supposed to be written as ``() -> ()``. I'm not 100% sure though.

**Comment by vocksel** [comment]
You are correct that there is a difference between `nil` and "nothing." I'm not sure what distinction Luau makes here either though

**Comment by vocksel** [comment]
`() -> ()` is the correct way to represent a function that returns "nothing," so we can move forward with swapping out functions that are currently annotated as returning `nil` when they actually don't
