### ISSUE TITLE
Support for non-Roact stories

### ISSUE THREAD

**Issue by passhley** [vocksel/flipbook#86]
AFAIK, at the moment our implementation only supports Roact components. With there being Fusion and other options to make UI now I believe it would be good to look into supporting them as well.

**Comment by passhley** [comment]
Technically, we do support all options for previewing stories, since we allow hoarcekat story files to work. However I'm more interested in getting controls supported for the other ways. I presume with Fusion we can do the same exact situation we currently have with Roact files where we could just do something like

```lua
-- Checkbox.story.lua

local Checkbox = require("Checkbox")

return {
	controls = {
		enabled = true,
	},

	story = function(props)
		return New Checkbox {
			enabled = props.enabled,
		}
	end
}
```

The hard part has to do with other, more native styles of UI development. This includes the classic way
of using OOP classes. Something I had come up with when I was working on this by myself was to change
the controls to look something more like

```lua
-- Checkbox.story.lua

local Checkbox = require("Checkbox")

return {
	controls = {
		enabled = {
			initialValue = true,
			onUpdated = function(component, newValue, oldValue)
				component:setEnabled(newValue)
			end
		}
	},

	story = function(props, mountingTarget)
		local component = Checkbox.new()
		component.Gui.Parent = mountingTarget

		return function()
			component:Destroy()
		end
	end
}
```
`onUpdated` would be called whenever the controls are changed in the previewer, and it would also be called
once on mounting.

Another thing I had in mind was in a developers `.storybook` file, we should
change the `roact` variable to be something more along the lines of `library`
to be more fitting for other stuff such as Fusion, and whatnot.

**Comment by vocksel** [comment]
I'm into this. I personally only use Roact which is why I've somewhat hardcoded it into the plugin. I think it would make sense to open up the possibility for _any_ UI framework to work with the plugin though.

**Comment by vocksel** [comment]
This is done as part of #154
