### ISSUE TITLE
Use absolute paths

### ISSUE THREAD

**Issue by vocksel** [vocksel/flipbook#93]
Currently we use frequent `script.Parent.Parent` chains to access other modules. Instead, we can define a variable that is assigned to `script:FindFirstAncestor("flipbook")`. From there all of our paths can be relative to the root of the plugin, rather than relative to the curent file

**Comment by passhley** [comment]
Oh yeah, that def. works with me, will start doing that from now on, and can go back and fix up other stuff aswell.

**Comment by passhley** [comment]
Issue regarding this, from what I can tell, that doesn't allow us to import types properly. ( unsure if this is affected in Studio itself, but this seems to be the case for VS )

**Comment by vocksel** [comment]
I swear nighttrains LSP has support for this. I'll double check later

**Comment by vocksel** [comment]
This should now be supported by Luau LSP
